### ISSUE TITLE
Is this library still maintained?

### ISSUE THREAD

**Issue by dsignr** [Zensavona/PayPal#4]
Hi, 
I'm planning to setup something with Paypal and was wondering if this library was still maintained, although you've mentioned you're still using it in production. 

Cheers.

**Comment by vinceurag** [comment]
I don't think it's still maintained since the author hasn't been active for a while. Anyway, I'm still using it in production (with just a few tweak, see my pull request #2). Works smoothly

**Comment by dsignr** [comment]
@vinceurag Thank you for the clarification :)

**Comment by FeeJai** [comment]
@Zensavona ping? Would you consider transferring ownership of this?

**Comment by Zensavona** [comment]
@FeeJai you are welcome to submit a PR or fork it if there is missing functionality you'd like to add :)
